name: Upgrade Node.js dependencies

on:
  schedule: # be scheduled when the workflow is pushed to default branch (e.g. master)
    - cron: '0 8 * * 2' # at 8:00 AM every Tuesday
  workflow_dispatch:
    inputs:
      upgrade_type:
        type: choice
        description: Upgrade type
        options:
          - latest
          - compatible
        default: latest

jobs:
  upgrader:
    runs-on: ubuntu-latest
    env:
      UPGRADE_TYPE: ${{ github.event.inputs.upgrade_type || 'latest' }}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'
      - run: pnpm install

      - name: Upgrade latest dependencies
        if: ${{ env.UPGRADE_TYPE == 'latest' }}
        run: |
          OUTDATED_DEPS=$(pnpm -r outdated || true)
          echo 'OUTDATED_DEPS<<EOF' >> $GITHUB_ENV
          echo "${OUTDATED_DEPS}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo 'UPGRADE_CMD=pnpm -r update --latest' >> $GITHUB_ENV
          pnpm -r update --latest

      - name: Upgrade compatible dependencies
        if: ${{ env.UPGRADE_TYPE == 'compatible' }}
        run: |
          OUTDATED_DEPS=$(pnpm -r outdated --compatible || true)
          echo 'OUTDATED_DEPS<<EOF' >> $GITHUB_ENV
          echo "${OUTDATED_DEPS}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo 'UPGRADE_CMD=pnpm -r update' >> $GITHUB_ENV
          pnpm -r update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore(deps): upgrade node.js dependencies'
          branch: upgrade-dependencies
          delete-branch: true
          title: Upgrade Node.js dependencies
          body: |
            This PR was automatically generated by the [upgrade](/actions/workflows/upgrade.yml) workflow by running the command: `${{ env.UPGRADE_CMD }}`

            Below is a list of all upgraded packages:

            ```
            ${{ env.OUTDATED_DEPS }}
            ```
          labels: |
            dependencies
